name: Build

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node inst
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm vers ğŸ—ï¸
        run: |
          npm --version

      - name: Install Packages ğŸ§³
        run: |
          npm install --legacy-peer-deps
          npm install --legacy-peer-deps -ws
      - name: Install Packages front ğŸ§³
        working-directory: ./packages/frontend
        run: |
          npm install --legacy-peer-deps

      - name: Lint check
        run: |
          npm run lint

      - name: Run  Jest  T-E-S-T
        run: |
          npm run test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0

      - name: webpack  build
        run: |
          npm run build


